### ISSUE TITLE
Not loading song on Safari

### ISSUE THREAD

**Issue by pedropcamellon** [michaelbromley/soundcloud-visualizer#12]
I tried loading "https://m.soundcloud.com/nba-youngboy/youngboy-never-broke-again-put" in Safari on my IPhone and it's not working. 
My name is Pedro Pablo Camellon. I just discovered the project and want to help. I know a little about UI/UX design, HTML, CSS, and JavaScript. I'd be really glad to contribute to your project.

**Comment by michaelbromley** [comment]
Hi!
I've not touched this code for many, many years, so I'm not surprised that some things might have stopped working.

You are very welcome to work on improving it, and I'll gladly accept pull requests fixing any issues you find!

**Comment by pedropcamellon** [comment]
These is what I get on the console of Edge v103 on Windows:
```
Mixed Content: 
The page at 'https://www.michaelbromley.co.uk/experiments/soundcloud-vis/?#muse/undisclosed-desires' was loaded over HTTPS, but requested an insecure script 'http://connect.soundcloud.com/sdk.js'. This request has been blocked; the content must be served over HTTPS.
app.js:455 
        
Uncaught ReferenceError: SC is not defined
  at SoundcloudLoader.loadStream (app.js:455:9)
  at loadAndUpdate (app.js:604:16)
  at init (app.js:626:9)
```

I think is beacause of this line: `<script src="https://connect.soundcloud.com/sdk.js"></script>`. It is not on the live version. This was pointed out in #9 :(
